#
# This source file is part of the Continous Delivery open source project
#
# SPDX-FileCopyrightText: 2022 Paul Schmiedmayer <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Release Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  webservice:
    name: Web Service Docker Image
    runs-on: ubuntu-latest
    needs: buildandtest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get latest tag
      id: latesttag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: latest
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push docker image
      id: buildandpush
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./WebService/Dockerfile
        push: true
        tags: ghcr.io/pschmiedmayer/continousdelivery:latest,ghcr.io/pschmiedmayer/continousdelivery:${{ steps.latesttag.outputs.tag }}
    - name: Image digest
      run: echo ${{ steps.buildandpush.outputs.digest }}
