#
# This source file is part of the Continous Delivery open source project
#
# SPDX-FileCopyrightText: 2022 Paul Schmiedmayer <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: SwiftLint

on:
  pull_request:
  workflow_dispatch:

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
      env:
        DIFF_BASE: ${{ github.base_ref }}
